steps:
#step 1
- name: 'gcr.io/cloud-builders/docker' 
  entrypoint: 'bash'
  args: [
   '-c', 
   'docker pull gcr.io/$PROJECT_ID/nginx:latest || exit 0'
  ]
#step 2 
- name: 'gcr.io/cloud-builders/docker'
  args: ['build','-t','gcr.io/my-project-56312-343412/nginx:v1.0','.']
#step 3
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'k8s/']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
  - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-1'
#step 4
- name: 'gcr.io/cloud-builders/kubectl'
  args: [
   'set', 
   'image', 
   'deployment', 
   'nginx', 
   'nginx=gcr.io/$PROJECT_ID/hello:$TAG_NAME'
  ]
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=<cluster-zone>'
  - 'CLOUDSDK_CONTAINER_CLUSTER=<cluster-name>'
# push images to Google Container Registry with tags
images: [
   'gcr.io/$PROJECT_ID/nginx:$TAG_NAME',
   'gcr.io/$PROJECT_ID/nginx:latest'
  ]
